version: 1
policy:
  pullRequests: public
tasks:
  $let:
    should_run:
      $if: 'tasks_for == "github-pull-request"'
      then: {$eval: 'event["action"] in ["opened", "reopened", "synchronize"]'}
      else: {$eval: 'tasks_for == "github-push"'}
    clone_url:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.clone_url}
      else: ${event.repository.clone_url}
    sha:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else: ${event.after}
  in:
  - $if: should_run
    then:
      taskId: {$eval: as_slugid("test")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '2 hours'}
      provisionerId: proj-taskcluster
      workerType: ci
      payload:
        maxRunTime: 3600
        image: 'golang:1.9-stretch'
        command:
          - /bin/bash
          - '-c'
          - >-
            mkdir -p /go/src/github.com/taskcluster/terraform-provider-jsone &&
            cd /go/src/github.com/taskcluster/terraform-provider-jsone &&
            git clone ${clone_url} . &&
            git config advice.detachedHead false &&
            git checkout ${sha} &&
            go get -v -d -t ./... &&
            go test -v -race ./...
      metadata:
        name: terraform-provider-jsone
        description: runs tests for terraform-provider-jsone
        owner: taskcluster-internal@mozilla.com
        source: ${clone_url}
